toml [build]
  command = "echo 'No main build command needed for Go Functions'"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/go-backend/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://valorant-abusing-frontend.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
